"""Add required_skills to jobs table

Revision ID: bf0eb048b58a
Revises: dc92dda28c7e
Create Date: 2025-07-06 12:35:20.902135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0eb048b58a'
down_revision: Union[str, Sequence[str], None] = 'dc92dda28c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('required_skills', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'required_skills')
    # ### end Alembic commands ###
