"""Add default value for application_date in candidates

Revision ID: dc92dda28c7e
Revises: b605bb46aaca
Create Date: 2025-07-06 08:54:55.050410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc92dda28c7e'
down_revision: Union[str, Sequence[str], None] = 'b605bb46aaca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('years_of_experience', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'years_of_experience')
    # ### end Alembic commands ###
